FROM node:14.13-buster

EXPOSE 8080

RUN npm install -g vue       
# + vue@2.6.12
RUN npm install -g @vue/cli
# + @vue/cli@4.5.7

CMD ["sleep", "infinity"]

#CMD ["npm", "run", "serve"]
# $ vue create research-environment-client
#   > interactive, Vue 2
# $ cd research-environment-client/
# $ npm run serve